node = "100.24.11.77:30052"

[[accounts]]
  name = "bpc-operations"
  address = "ndakj49v6nnbdq3yhnf8f2j6ivfzicedvfwtunckivfsw9qt"
  [accounts.root]
    path = "/"
    public = "npuba4jaftckeeb4eb3ur3ubmg38skak7bbinycna8dudjx8ka7emzjpx4bvpzp43daaaaaaaaaaaaak9srd4ru8uj3rsmxghk32jfmkjgqvrff2s6axjrqyyn9h7fetzr7rndpaec3k"
    private = "npvta8jaftcjebhe9pi57hji5yrt3yc3f2gn3ih56rys38qxt52945vuf8xqu4jfkaaaaaaaaaaaacz6d28v6zwuqm6c7jt4yqcjk4ujvw53jqehafkm5xxvh39jjep58u7pw33dd7cc"
  [accounts.ownership]
    path = "/44/20036/100/1"
    public = "npuba4jaftckeebyrmpkw4ap7jae22wyb83ncdseuwpvfibunh5fi8id6vs2he86jwieh856caaaaaasjfhkhw6npur6sgxy3r5b4i2hxhqia3w9dm2kz8tgkgf5k5jm88c5htkhhpt8"
    private = "npvta8jaftcjea9en4tr26txweh3fkejikikubnn7mthymvir3292cquaphxr2egybb9y9asaaaaaecjj4t7hddnv9ebxpym82qugb7j5uagph248cx9wjuttq4y4k9zs43vvnn3z9tw"

[rfe]
  address = "ndnbk3z55e8tz4zit8um4gfs7uwn9pm9qhhbssv6h5xi4gce"
  keys = ["npvtayjadtcbid79zr2euhnu3auqfr45gbe26r6yx9zw68ds8cmxh93f6gp7zyi9uh2dzeg7htx8whbxrgmseuexfjsusmh8zg35wvg589upjahd2qv7qk2e88a8"]

[nnr]
  address = "ndnakdruaz8stkmjrw9axqe5zt2ptgbg5sqx3u6a937xvzhw"
  keys = ["npvtayjadtcbib6fyr7vq4zs3eu5nnydfg4k7nnyx6vbks4ac9q6eru4xf25m85k3h57tfncznrs63csb55h6mk9qpskehz9q9gef59hitpnhgrm8xes4r4dbqt4"]

[cvc]
  address = "ndnpdz38s29pre6dnpmn8tnaexfbf6mjqexz4wdf37m42p8n"
  keys = ["npvtayjadtcbiceq35u2hxyudvevwjkbe4naysvqsm8qckjvm7nptjjj5rpqzaha8bwyjyi9b6uuccvr5vgikimghexf692gwpfjiyyau2277mr3ncehs96yj2rh"]

[record_price]
  address = "ndnk2ucu2qpeajxp6yvq2qjs4i33nhxkryysimgwa7gzucc6"
  keys = ["npvtayjadtcbia7mrjumkham3vqif2sxqzs7uu4rw6c8df9fk57npd5q64vmqr5tameyiybwbvtxu7vzcg9et29i3hw8y48wmkxvek3zmwp5yybz7mj97a42qc8x"]

[set_sysvar]
  address = "ndnqccagas6vys68zzj345shxdwdgjq2vc93viajkrryb3ic"
  keys = ["npvtayjadtcbibyjmm7iks6s8w9ipbkfr4qf2tbczvzwbgksg3kyb5smu4fdwfcz3my5rab9p2imw2ahgaqyxq4n5ixukwpce626d4iqfz6vsrq8kbxpgw4p3kdv"]
