CommandValidatorChangeAddress = "ndnpdz38s29pre6dnpmn8tnaexfbf6mjqexz4wdf37m42p8n"
CommandValidatorChangeOwnership = "npuba8jadtbbedabswauez3rpm7j35g2wtafgdecavkvmqhmtxrjztq3c8s4b8jqct26v3mwcwtp"
CommandValidatorChangeOwnershipPrivate = "npvtayjadtcbibvzrvu9y56ciff5smcuerccxtdn7bynnhuf9r9czmakuwbrqzuxhsa2kajcm6zyx8w67vnkiscvbubajxjxzdx24zw52zntripa9ezbxmjp22tt"
CommandValidatorChangeValidation = "npuba8jadtbbeadjnvnt8d3feefg9zgnswsynqjkm39spi4kutpnbftt54y9u2eiqcnvk6c57wf8"
CommandValidatorChangeValidationPrivate = "npvtayjadtcbiceq35u2hxyudvevwjkbe4naysvqsm8qckjvm7nptjjj5rpqzaha8bwyjyi9b6uuccvr5vgikimghexf692gwpfjiyyau2277mr3ncehs96yj2rh"
NominateNodeRewardAddress = "ndnakdruaz8stkmjrw9axqe5zt2ptgbg5sqx3u6a937xvzhw"
NominateNodeRewardOwnership = "npuba8jadtbbec3kenugkz8jxf2j3f5aveyne33nfyidbtdxedsnjh596muz9xxwsfg934jksfz3"
NominateNodeRewardOwnershipPrivate = "npvtayjadtcbibbgindqtv5b8uru25pcxxzneh82tja8xd9rdpr6ci943agupdu4pnxcgjdfm9e4u6e6u7sjumgcn6yc5ebs2t4ub2gev798f3m9444ikxjqch6w"
NominateNodeRewardValidation = "npuba8jadtbbecrz5ck2fq29b3ufadzyr2yx865awirr878nimz8qtc42qn8z7kjbx3cqrfdsz4a"
NominateNodeRewardValidationPrivate = "npvtayjadtcbib6fyr7vq4zs3eu5nnydfg4k7nnyx6vbks4ac9q6eru4xf25m85k3h57tfncznrs63csb55h6mk9qpskehz9q9gef59hitpnhgrm8xes4r4dbqt4"
RecordPriceAddress = "ndnk2ucu2qpeajxp6yvq2qjs4i33nhxkryysimgwa7gzucc6"
RecordPriceOwnership = "npuba8jadtbbeapipvpc57hnekquqfdq3eiiexrsgmdyidsrnzuic339uay48any6fbkwgh37cxb"
RecordPriceOwnershipPrivate = "npvtayjadtcbicwunj3tqjbgpjv5cv8264v6yjfiaaqjyv2y86pir932c6ubmbj66gwg3ytp8vycfhjhctznueeckz2dft5eb2hym3ebn693ampragmqkqj3y3ux"
RecordPriceValidation = "npuba8jadtbbeayjntndidhdmf5hqep8jdt8turj7px7iyxmgixvqzi5zpndr4yv82vphvhqjyxb"
RecordPriceValidationPrivate = "npvtayjadtcbia7mrjumkham3vqif2sxqzs7uu4rw6c8df9fk57npd5q64vmqr5tameyiybwbvtxu7vzcg9et29i3hw8y48wmkxvek3zmwp5yybz7mj97a42qc8x"
ReleaseFromEndowmentAddress = "ndnbk3z55e8tz4zit8um4gfs7uwn9pm9qhhbssv6h5xi4gce"
ReleaseFromEndowmentOwnership = "npuba8jadtbbeakudue8fffpcmdzsz39ucumg7c7u6t8p7f5g4rejih3srrw8pvm3p2r3xv4bhyu"
ReleaseFromEndowmentOwnershipPrivate = "npvtayjadtcbicez67hig4h87rq7bz9ew6fdgt6dkt27iu9yejtb8m82hrhwq56mnfjb3crcuuytft52m693bjfvqtq3qi9g8u7vphuewd62hz4rg3x6brmwq6nc"
ReleaseFromEndowmentValidation = "npuba8jadtbbearshqip4rdm7iqdk8nzajejkkvbfayr7qpvzjgpz79e4uaqhs7h5i8zt3hxhebv"
ReleaseFromEndowmentValidationPrivate = "npvtayjadtcbid79zr2euhnu3auqfr45gbe26r6yx9zw68ds8cmxh93f6gp7zyi9uh2dzeg7htx8whbxrgmseuexfjsusmh8zg35wvg589upjahd2qv7qk2e88a8"
SetSysvarAddress = "ndnqccagas6vys68zzj345shxdwdgjq2vc93viajkrryb3ic"
SetSysvarOwnership = "npuba8jadtbbedqs2nu7eb8gte95fn5nie5ai5mvwfyncuazc2ij7z2ei9n7sygz3kh2ju6hsqj9"
SetSysvarOwnershipPrivate = "npvtayjadtcbia2kjj8ws8nce6gaxzwyrrretd5ph3bnv8pcebvwban8rb7ku4ewpzingjqua9diur7uypyecpsepx34c5gbjamtnee856ceryq2mdm6dghkarc9"
SetSysvarValidation = "npuba8jadtbbeczpy8ad85sszjsaqna7pk7w3ytmexi4ej3t2hws6mr3ha876wdk4jbcd5d9e9d6"
SetSysvarValidationPrivate = "npvtayjadtcbibyjmm7iks6s8w9ipbkfr4qf2tbczvzwbgksg3kyb5smu4fdwfcz3my5rab9p2imw2ahgaqyxq4n5ixukwpce626d4iqfz6vsrq8kbxpgw4p3kdv"
