path = "./ndau.xlsx"
sheet = "Web Dashboard"
first_row = 6
noms_path = "~/.ndau/ndau/noms::ndau"

[columns]
  address = 3
  notify_immediately = 8
  purchase_date = 0
  qty_purchased = 1
  unlock_date = 4
