path = "./ndau.xlsx"
sheet = "Web Dashboard"
first_row = 6
noms_path = "$HOME/.ndau/ndau/noms"
genesis = 2018-09-01T00:00:00Z

[columns]
  address = 3
  notify_immediately = 8
  purchase_date = 0
  qty_purchased = 1
  reward_target = 6
  unlock_date = 4
