node = "https://testnet-0.ndau.tech:26670"

[[accounts]]
  name = "bpc-operations"
  address = "ndbmgby86qw9bds9f8wrzut5zrbxuehum5kvgz9sns9hgknh"
  [accounts.ownership]
    public = "npuba8jadtbbeaxuga2i8sc3t9hr6t8c9wnv6z6zxi693w3xthiurq6mnyxye2zd6iyh3ppy9ywp"
    private = "npvtayjadtcbidnizwetc9k7tnmqzn7drw5vpaxkaquaw2rj3gkmtt7yrgrqn84wyk3daneribn29vz8i9br4gj8m8m4wqr64n42vwjhzqfymk5cnmt8rf33yty8"

  [[accounts.transfer]]
    public = "npuba8jadtbbeauynymbi2rhz6tadb49bbq8qgtt9g3cjxfue86za4xuq8eqjr78kg6z3u74i6zc"
    private = "npvtayjadtcbibyuu32djwmh3spdcr9a2hrgbnifefuvt6bkmdzhvw4g5g75iyqgwjmgmfswnhv58isbs7rsszrhdi29vnte4u3crqmspk3hrchez89f62z4c4w9"

  [[accounts.transfer]]
    public = "npuba8jadtbbedh567fc6w9h7imhqcx8ywhyf9ikfavamm7hbcs6v5n7u7jb9wd8uz6xtwwq6mmt"
    private = "npvtayjadtcbib4uu3aggbzbvpssxeg693vcxyceybscbix3hi2inuegmcw4hyyr3v78qutqkrv8wfvzbk9mkd5c9wfcsjsfx8vstiqj7yq3qws94b9jmph97r2x"

  [[accounts.transfer]]
    public = "npuba8jadtbbedpqchprc4kavtxd4ef3ue663j9tf59uuwg3b6kbhbmi6an3ubrugss5ijn5uiyq"
    private = "npvtayjadtcbia2fgfvp46n2euhcg9hagdzkyczqhpcuav9vjctitqy5ic4pxcp3hyzbdyztpfaj24t7cc63cqqnw92u793jkdns8favsxwqagn3az3d8fbjdf68"

  [[accounts.transfer]]
    public = "npuba8jadtbbea3hrnm7cjz439zfzx7fs58emnug8jiszg7rph5ite7izhy9bwig8vxwe7trqcde"
    private = "npvtayjadtcbicahy9ztp7fsvyp2anvccn9mfgzc26qq9sc3wfhf4anz2gsetb8h6nvzyf8te57n95u548u2p9cfyjdrewimvqzyv7wiuqwmv5rs4edrazvkwemg"

  [[accounts.transfer]]
    public = "npuba8jadtbbed5admvfhdbc4xrqcrzva6xbhgsde8rtggzkrts5xzzhznayabdjhrh822rez2pz"
    private = "npvtayjadtcbibippr63sypsksgv5hf26egcj4nkjqxhk6jkqr3dif3xphszcb2mj7sbx3uvtstpkzzbh53sqksvviburh2vdmxh22p455v5yamaatwvkmxhjb7w"

  [[accounts.transfer]]
    public = "npuba8jadtbbeag92g85qfzktzzam5hhxf8xd6jaudrbmey6s5d3wb5x58tu58f7egjvu6ynrkbi"
    private = "npvtayjadtcbibduviibtua4dmqgzakeqqitk5ceigwnzvqtp92wzxg2n8aygg8iwdr6drpzc5xi55sf7vv4u9kt8esjbzsxumqipt64a7479i3p9c8ug7tisys2"

  [[accounts.transfer]]
    public = "npuba8jadtbbeanrtnfudcvsxe42fth8rzgarv3sefpyx4u4c4vq2f8asdmgi79dsh5m35mpqukv"
    private = "npvtayjadtcbidzjbv8da9cz8uxacmwzycux4wsfj32mzxhne9afdh6bgd85fithcgh2yc3btj2kupnc2v9h5vah362ccy5k7jpbpjznc9aibxveq9t2pvi5wpzw"

  [[accounts.transfer]]
    public = "npuba8jadtbbecffxp8anng5fxmzb3airn4kszguinmp49nkvzeqjjf56mccsg4tbukbcbkd4bg8"
    private = "npvtayjadtcbicnvjprwsqu4rawfvgnbex3acg99wv4jgp8urphykuqakd63338rbcu4y9aggdpu4x5s6sehypfimvjegfy7ryfj5uhewu78ftbidpisrx3mw26w"

  [[accounts.transfer]]
    public = "npuba8jadtbbebngzgbjvnsknns9gjznsw92cz65hhqje89fbr5er3bv7rhzrk3cwx9rxkyaskwe"
    private = "npvtayjadtcbiaavu4e4zen7bxj87mfuchpuwuwmds5mu2d32t252ttimybpztj5uydmvaw3yifggirve5yikr6bm8pvvzeurrusz7uh6s38zv5zxntkh35kjrum"

[rfe]
  address = "ndeeh86uun6us9cenuck2uur679e37uczsmys33794gnvtfz"
  keys = ["npvtayjadtcbib2u2rnem47vgqqifsbt8r8y2ktdygtfkaw98imgpjw25mqztt72b7k2scgjyhypk4twibph5m88sw3xmg3xe77m9vmsyfhq32ywn7z63bmm4zix","npvtayjadtcbian9xk7kr3cvik7h56ez5i3fwzab3pivkbb5deaka5cdqy5e7ydx59wfejb3wkjmuki9mtmgxwytwwwy4p2s4zxyrbq5fw8sphuzak76yskvjkig","npvtayjadtcbibdffjpz8btfrrxtaynhpckt5aycqievx6atk5ni7kn8f65ypw9gathwu5w6mmryfg2iavci3fs3puhaespn2wujg6se2qf6vjnhgy8hcckbhqud"]

[nnr]
  address = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
  keys = ["npvtayjadtcbicjrtcnf64umrrukbzfarpka7b5kkm74fufq3n6fmmtn8cp8cbaqms8kgj383vkgzesa3hrwbjeaq8b5q7dxg75webmwjc4ahf3wjr3rxvdvvfwz","npvtayjadtcbicy2dz5fexykde23wytipi8ydnhvazxqu927zrcsh8uy2ztpghhh2m2w5pnvz2e9iig682hq9z2zmc2kbgtyrdvbww952ditp7d8ifa899hj9d6v","npvtayjadtcbid48pwtyq5ygrwcsiah5966a4xsa5pyhxacayz8wemtjp4riivv8jmrgagfnaz54g9gdavh9dw4u8c5wrz7223h85y253ie4q9attdqwuk2835cf"]

[cvc]
  address = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
  keys = ["npvtayjadtcbicjrtcnf64umrrukbzfarpka7b5kkm74fufq3n6fmmtn8cp8cbaqms8kgj383vkgzesa3hrwbjeaq8b5q7dxg75webmwjc4ahf3wjr3rxvdvvfwz","npvtayjadtcbicy2dz5fexykde23wytipi8ydnhvazxqu927zrcsh8uy2ztpghhh2m2w5pnvz2e9iig682hq9z2zmc2kbgtyrdvbww952ditp7d8ifa899hj9d6v","npvtayjadtcbid48pwtyq5ygrwcsiah5966a4xsa5pyhxacayz8wemtjp4riivv8jmrgagfnaz54g9gdavh9dw4u8c5wrz7223h85y253ie4q9attdqwuk2835cf","npvtayjadtcbibyuu32djwmh3spdcr9a2hrgbnifefuvt6bkmdzhvw4g5g75iyqgwjmgmfswnhv58isbs7rsszrhdi29vnte4u3crqmspk3hrchez89f62z4c4w9"]

[record_price]
  address = "ndmmw2cwhhgcgk9edp5tiieqab3pq7uxdic2wabzx49twwxh"
  keys = ["npvtayjadtcbiay3k5aftcrdbrbkkvnufghfc9cj34nfdkwifrdgrshjszng9bu6u4frr7nvb5kfi3zhpkjx96eizb9w5q2z3xj2z3mzh2fvnq6dgzxsheimb3eu","npvtayjadtcbidpdhmxdnkd3bfzz2u39tvyufxmiaxf8tps5a7edm55v4pns8bercrm23ftkcry4a6f9pc6eyj9knjeavha3ky6d8vs8k2ge5tcy5py59484rfr3","npvtayjadtcbica7z8vkkvcaknt6em3ivzv3piz6bz8k75a6htchtz2a6cnyr3siui2rh5qm4kciqaktjbfvbsk34a4uz96jzhsqpmkajuv3mgs9s8epdqn5kp4k"]

[set_sysvar]
  address = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
  keys = ["npvtayjadtcbicjrtcnf64umrrukbzfarpka7b5kkm74fufq3n6fmmtn8cp8cbaqms8kgj383vkgzesa3hrwbjeaq8b5q7dxg75webmwjc4ahf3wjr3rxvdvvfwz","npvtayjadtcbicy2dz5fexykde23wytipi8ydnhvazxqu927zrcsh8uy2ztpghhh2m2w5pnvz2e9iig682hq9z2zmc2kbgtyrdvbww952ditp7d8ifa899hj9d6v","npvtayjadtcbid48pwtyq5ygrwcsiah5966a4xsa5pyhxacayz8wemtjp4riivv8jmrgagfnaz54g9gdavh9dw4u8c5wrz7223h85y253ie4q9attdqwuk2835cf"]
