node = "https://testnet-0.ndau.tech:26670"

[[accounts]]
  name = "bpc-operations"
  address = "ndbmgby86qw9bds9f8wrzut5zrbxuehum5kvgz9sns9hgknh"
  [accounts.ownership]
    public = "npuba8jadtbbeaxuga2i8sc3t9hr6t8c9wnv6z6zxi693w3xthiurq6mnyxye2zd6iyh3ppy9ywp"
    private = "npvtayjadtcbidnizwetc9k7tnmqzn7drw5vpaxkaquaw2rj3gkmtt7yrgrqn84wyk3daneribn29vz8i9br4gj8m8m4wqr64n42vwjhzqfymk5cnmt8rf33yty8"

  [[accounts.transfer]]
    public = "npuba8jadtbbecqu6ehdvi3ag2m5x5cghbrzjb9r5h9ptmnnau6kfsmzdjtvkpep7tqavqbk2yb4"
    private = "npvtayjadtcbibku43344uqmrn9kaifw4nf3szuue8gep73zcdqrpq3tab3qqxw8rhjqcdt3wnsdnf747tddsz5ws9z7v9y2xygajqfc2f5tw23xgug8xjzz2nru"

  [[accounts.transfer]]
    public = "npuba8jadtbbedunr8g6sn8yvh8shc336xdiafgnggptvpv9m93hsjwryvsa665vy3ns2k499524"
    private = "npvtayjadtcbic4aregt9ni3w4njqtyniseskq6knu5cajnxx42ntwwaq2ammi9dr3gh9dqigrmjv9idtn68ktwacvgddg23y39x96v2e4h5j2aqqp355wh2byix"

  [[accounts.transfer]]
    public = "npuba8jadtbbebqjifq8iiwkjgg4bqi8gp92cc9sziubydp5vh7x2se8uygrsgrmeaq2vbpq3vch"
    private = "npvtayjadtcbib94iw83xfjuez788xf82v9f5iq4ddf54vj85r5bexg564xk6pw9kzewczreekfevdpazerdg96bbr2mwja5by73v846icrjmdh2dhxup3c3gpex"

[rfe]
  address = "ndeeh86uun6us9cenuck2uur679e37uczsmys33794gnvtfz"
  keys = ["npvtayjadtcbib2u2rnem47vgqqifsbt8r8y2ktdygtfkaw98imgpjw25mqztt72b7k2scgjyhypk4twibph5m88sw3xmg3xe77m9vmsyfhq32ywn7z63bmm4zix","npvtayjadtcbian9xk7kr3cvik7h56ez5i3fwzab3pivkbb5deaka5cdqy5e7ydx59wfejb3wkjmuki9mtmgxwytwwwy4p2s4zxyrbq5fw8sphuzak76yskvjkig","npvtayjadtcbibdffjpz8btfrrxtaynhpckt5aycqievx6atk5ni7kn8f65ypw9gathwu5w6mmryfg2iavci3fs3puhaespn2wujg6se2qf6vjnhgy8hcckbhqud"]

[nnr]
  address = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
  keys = ["npvtayjadtcbicjrtcnf64umrrukbzfarpka7b5kkm74fufq3n6fmmtn8cp8cbaqms8kgj383vkgzesa3hrwbjeaq8b5q7dxg75webmwjc4ahf3wjr3rxvdvvfwz","npvtayjadtcbicy2dz5fexykde23wytipi8ydnhvazxqu927zrcsh8uy2ztpghhh2m2w5pnvz2e9iig682hq9z2zmc2kbgtyrdvbww952ditp7d8ifa899hj9d6v","npvtayjadtcbid48pwtyq5ygrwcsiah5966a4xsa5pyhxacayz8wemtjp4riivv8jmrgagfnaz54g9gdavh9dw4u8c5wrz7223h85y253ie4q9attdqwuk2835cf"]

[cvc]
  address = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
  keys = ["npvtayjadtcbicjrtcnf64umrrukbzfarpka7b5kkm74fufq3n6fmmtn8cp8cbaqms8kgj383vkgzesa3hrwbjeaq8b5q7dxg75webmwjc4ahf3wjr3rxvdvvfwz","npvtayjadtcbicy2dz5fexykde23wytipi8ydnhvazxqu927zrcsh8uy2ztpghhh2m2w5pnvz2e9iig682hq9z2zmc2kbgtyrdvbww952ditp7d8ifa899hj9d6v","npvtayjadtcbid48pwtyq5ygrwcsiah5966a4xsa5pyhxacayz8wemtjp4riivv8jmrgagfnaz54g9gdavh9dw4u8c5wrz7223h85y253ie4q9attdqwuk2835cf","npvtayjadtcbibku43344uqmrn9kaifw4nf3szuue8gep73zcdqrpq3tab3qqxw8rhjqcdt3wnsdnf747tddsz5ws9z7v9y2xygajqfc2f5tw23xgug8xjzz2nru"]

[record_price]
  address = "ndmmw2cwhhgcgk9edp5tiieqab3pq7uxdic2wabzx49twwxh"
  keys = ["npvtayjadtcbiay3k5aftcrdbrbkkvnufghfc9cj34nfdkwifrdgrshjszng9bu6u4frr7nvb5kfi3zhpkjx96eizb9w5q2z3xj2z3mzh2fvnq6dgzxsheimb3eu","npvtayjadtcbidpdhmxdnkd3bfzz2u39tvyufxmiaxf8tps5a7edm55v4pns8bercrm23ftkcry4a6f9pc6eyj9knjeavha3ky6d8vs8k2ge5tcy5py59484rfr3","npvtayjadtcbica7z8vkkvcaknt6em3ivzv3piz6bz8k75a6htchtz2a6cnyr3siui2rh5qm4kciqaktjbfvbsk34a4uz96jzhsqpmkajuv3mgs9s8epdqn5kp4k",]

[set_sysvar]
  address = "ndnf9ffbzhyf8mk7z5vvqc4quzz5i2exp5zgsmhyhc9cuwr4"
  keys = ["npvtayjadtcbicjrtcnf64umrrukbzfarpka7b5kkm74fufq3n6fmmtn8cp8cbaqms8kgj383vkgzesa3hrwbjeaq8b5q7dxg75webmwjc4ahf3wjr3rxvdvvfwz","npvtayjadtcbicy2dz5fexykde23wytipi8ydnhvazxqu927zrcsh8uy2ztpghhh2m2w5pnvz2e9iig682hq9z2zmc2kbgtyrdvbww952ditp7d8ifa899hj9d6v","npvtayjadtcbid48pwtyq5ygrwcsiah5966a4xsa5pyhxacayz8wemtjp4riivv8jmrgagfnaz54g9gdavh9dw4u8c5wrz7223h85y253ie4q9attdqwuk2835cf"]
